### PR TITLE
Fix OpenAL cmake error above CMake 3.11

### PR DESCRIPTION
**Pull request by bluekyu**
After CMake 3.11, OpenAL build causes cmake error because of "CHECK_INCLUDE_FILES" macro.
(In CMake 3.11, the macro checks if additional arguments are is valid, or not.)

OpenAL master branch has already a patch:
https://github.com/kcat/openal-soft/commit/cae4b1a062b53dd25eba7caa41622be730106749

So, I created "openal.cmake" with the patch.

### CODE REVIEW

**Comment by rdb** [comment]
Is there a good reason we shouldn't just update to the latest commit of OpenAL Soft?

**Comment by bluekyu** [comment]
No. Just, I thought that keeping the version is better at this moment. Also, new version with the patch is not released, yet.

But if the update has not problem, then I think it is the best.

**Comment by bluekyu** [comment]
I tested compiling Panda3D with the latest OpenAL and ran Music Box sample. These were good.
But I could not test more because I does not have other sound samples.

**Comment by rdb** [comment]
OK, I would suggest that we just upgrade OpenAL Soft to the latest version.

**Comment by rdb** [comment]
Actually, it looks like the latest version of OpenAL Soft requires CMake 3.0.  We still need to build with as low as CMake 2.8.11.2.

**Comment by rdb** [comment]
Addendum: the need to continue supporting CMake 2.8.11.2 has gone away.  We are free to update these packages to their latest versions.

**Pull request closed without merging**
